language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
  - arm64
services:
  - xvfb
julia:
  - 1.0.5
  - 1.4
  - nightly
branches:
  - only:
    - master
matrix:
  allow_failures:
    - julia: nightly
    - arch: arm64
  exclude:
    - os: osx
      arch: x86
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64
notifications:
  email: false
