language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0.4
  - 1.1
  - 1.2
  - nightly
branches:
  - only:
    - master
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
